# Generated by Django 3.1.5 on 2021-02-02 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210202_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_id',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
    ]
